image: debian:10.2-slim

stages:
  - build
  - deploy

build:
  image: docker:19.03.1
  stage: build
  services:
    - docker:19.03.1-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    refs:
      - master

trigger_deploy:
  stage: deploy
  script:
    # Install curl
    - 'which curl || (apt-get update -y && apt-get install curl -y)'

    # Trigger pipeline in mister-deploy project
    - curl
      --request POST
      --form token=$CI_JOB_TOKEN
      --form ref=master
      --form variables[SERVICE_NAME]=toastme
      https://gitlab.com/api/v4/projects/16132375/trigger/pipeline
  only:
    refs:
      - master
  when: manual
